#!/usr/bin/env python3
"""Generate the vendored ``skills/<skill>/scripts/fmp_client.py`` (and
``_fmp_compat.py``) from the canonical source under ``scripts/fmp_client/``
(Issue #115).

Each skill is rendered from ``core_template.py.tmpl`` + the extension blocks
listed in ``registry.py``. The template carries the evolved vcp-screener core;
``# @@IF <flag>`` / ``# @@ELSE`` / ``# @@ENDIF`` blocks toggle the family-A quote
surface (``has_quote``) and family-B budget surface (``budget``), and ``@@TOKEN@@``
markers fill in the title, feature bullets, historical-window default, class
constants, and extension methods.

Usage::

    python3 scripts/generate_fmp_client.py            # write the vendored files
    python3 scripts/generate_fmp_client.py --check    # drift gate (exit 1 on drift)

Mirrors the repo's existing generator drift gates (see
``scripts/generate_catalog_from_index.py``): ``--check`` prints ``DRIFT:`` / ``OK:``
to stderr and returns 1 when any vendored file differs from the regenerated output.
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = REPO_ROOT / "scripts" / "fmp_client"

BANNER = (
    "# GENERATED by scripts/generate_fmp_client.py — do not edit.\n"
    "# Source of truth: scripts/fmp_client/ (core_template.py.tmpl, registry.py, extensions/).\n"
    "# Regenerate: python3 scripts/generate_fmp_client.py"
)

# Flags referenced by ``# @@IF <flag>`` markers in the template.
FLAGS = ("has_quote", "budget", "has_compat", "hist_return_list")


def _load_registry() -> dict:
    spec = importlib.util.spec_from_file_location("_fmp_registry", SRC_DIR / "registry.py")
    module = importlib.util.module_from_spec(spec)
    # Register before exec so @dataclass can resolve annotations via sys.modules.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module.SKILLS


def _process_conditionals(text: str, flags: dict) -> str:
    """Strip ``# @@IF/@@ELSE/@@ENDIF`` markers, keeping only the active branches."""
    out: list[str] = []
    stack: list[list] = []  # each frame: [flag_value, in_else]
    for line in text.splitlines(keepends=True):
        stripped = line.strip()
        if stripped.startswith("# @@IF "):
            flag = stripped[len("# @@IF ") :].strip()
            if flag not in flags:
                raise ValueError(f"Unknown template flag: {flag!r}")
            stack.append([bool(flags[flag]), False])
            continue
        if stripped == "# @@ELSE":
            stack[-1][1] = True
            continue
        if stripped == "# @@ENDIF":
            stack.pop()
            continue
        if all((fv if not in_else else (not fv)) for fv, in_else in stack):
            out.append(line)
    if stack:
        raise ValueError("Unbalanced # @@IF / # @@ENDIF in template")
    return "".join(out)


def _render_extensions(cfg) -> str:
    blocks = [
        (SRC_DIR / "extensions" / f"{name}.py.tmpl").read_text(encoding="utf-8")
        for name in cfg.extensions
    ]
    return "\n".join(blocks)


def render_fmp_client(cfg) -> str:
    """Render one skill's standalone ``fmp_client.py`` source text."""
    text = (SRC_DIR / "core_template.py.tmpl").read_text(encoding="utf-8")
    text = _process_conditionals(text, {f: getattr(cfg, f) for f in FLAGS})

    text = text.replace("# @@BANNER@@", BANNER)
    text = text.replace("@@TITLE@@", cfg.title)
    text = text.replace("@@FEATURES@@", "\n".join(cfg.feature_lines))
    text = text.replace("@@HIST_DAYS@@", str(cfg.hist_days))

    const_block = "".join(f"    {name} = {literal}\n" for name, literal in cfg.class_constants)
    text = text.replace("@@CLASS_CONSTANTS@@\n", const_block + "\n")

    text = text.replace("@@EXTENSIONS@@\n", _render_extensions(cfg) + "\n")
    # @@BATCH_DAYS@@ lives in the family_a_quote extension, so substitute after it.
    text = text.replace("@@BATCH_DAYS@@", str(cfg.batch_days))

    if "@@" in text:
        leftover = next(tok for tok in text.split("@@")[1:2])
        raise ValueError(f"Unsubstituted template token near: @@{leftover[:40]}")
    return text.rstrip("\n") + "\n"


def render_compat() -> str:
    """The canonical ``_fmp_compat.py`` (byte-identical to the PR0 vendored shim)."""
    return (SRC_DIR / "compat_v3_to_stable.py.tmpl").read_text(encoding="utf-8")


def _targets(cfg) -> list[tuple[Path, str]]:
    scripts_dir = REPO_ROOT / "skills" / cfg.skill / "scripts"
    targets = [(scripts_dir / "fmp_client.py", render_fmp_client(cfg))]
    if cfg.has_compat:
        targets.append((scripts_dir / "_fmp_compat.py", render_compat()))
    return targets


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify vendored files match the regenerated output; exit 1 on drift.",
    )
    args = parser.parse_args()

    skills = _load_registry()
    drift = False
    for cfg in skills.values():
        for path, content in _targets(cfg):
            rel = path.relative_to(REPO_ROOT)
            if args.check:
                current = path.read_text(encoding="utf-8") if path.exists() else None
                if current != content:
                    print(f"DRIFT: {rel} differs from regenerated output", file=sys.stderr)
                    drift = True
                else:
                    print(f"OK: {rel} matches", file=sys.stderr)
            elif path.exists() and path.read_text(encoding="utf-8") == content:
                print(f"Unchanged: {rel}", file=sys.stderr)
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
                print(f"Wrote {rel}", file=sys.stderr)

    return 1 if (args.check and drift) else 0


if __name__ == "__main__":
    sys.exit(main())
